if vim.g.vscode then
  return {}
end

return {
  { import = "lazyvim.plugins.extras.lang.rust" },

  -- {
  --   "mrcjkb/rustaceanvim",
  --   ft = { "rust" },
  --   opts = function()
  --     vim.o.makeprg = "cargo build %"
  --     vim.keymap.set({ "n", "i" }, "<C-S>", "<cmd>wa | make!<cr>", { desc = "Save and make the file" })
  --   end,
  -- },
}

-- return {
--   {
--     "mrcjkb/rustaceanvim",
--     event = "VeryLazy",
--     version = "^3", -- Recommended
--     ft = { "rust" },
--     config = function()
--       vim.g.rustaceanvim = {
--         server = {
--           settings = {
--             ["rust-analyzer"] = {
--               cargo = { allFeatures = true },
--               checkOnSave = true,
--               check = {
--                 enable = true,
--                 command = "clippy",
--                 features = "all",
--               },
--               procMacro = {
--                 enable = true,
--               },
--             },
--           },
--         },
--       }
--     end,
--   },
--
--   {
--     "hrsh7th/nvim-cmp",
--     dependencies = {
--       {
--         "Saecki/crates.nvim",
--         event = { "BufRead Cargo.toml" },
--         opts = {
--           src = {
--             cmp = { enabled = true },
--           },
--         },
--       },
--     },
--     ---@param opts cmp.ConfigSchema
--     opts = function(_, opts)
--       local cmp = require("cmp")
--       opts.sources = cmp.config.sources(vim.list_extend(opts.sources, {
--         { name = "crates" },
--       }))
--     end,
--   },
--
--   {
--     "Saecki/crates.nvim",
--     event = { "BufRead Cargo.toml" },
--     opts = {
--       src = {
--         cmp = { enabled = true },
--       },
--     },
--   },
--
--   {
--     "rouge8/neotest-rust",
--   },
--
--   {
--     "nvim-neotest/neotest",
--     optional = true,
--     dependencies = {
--       "rouge8/neotest-rust",
--     },
--     opts = {
--       adapters = {
--         ["neotest-rust"] = {},
--       },
--     },
--   },
-- }
